### ISSUE TITLE
Add: SMSD TV Channel 18

### ISSUE THREAD

**Issue by ProPontifex** [iptv-org/database#14146]
### Channel Name

SMSD TV Channel 18

### Owners (optional)

Shawnee Mission School District

### Country

US

### Subdivision (optional)

US-KS

### City (optional)

Fairway

### Broadcast Area

s/US-KS

### Languages

eng

### Categories (optional)

education

### NSFW

FALSE

### Website (optional)

https://shawnee-mission-ks.cablecast.tv/CablecastPublicSite/watch-now?site=2

### Logo

https://resources.finalsite.net/images/f_auto,q_auto,t_image_size_2/v1528810052/smsdorg/ivcuoxjonhnqoeogiwhf/eSchoolLogo.png

**Comment by ProPontifex** [comment]
Just tried this: working fine here. Geo-blocked?

**Comment by freearhey** [comment]
The logo link fails validation due to the presence of a comma in it.

**Comment by ProPontifex** [comment]
Again, works fine here.

**Comment by freearhey** [comment]
No one said that the link is not working. It's just that in order for a link to pass validation there should be no commas in it. Otherwise the whole database will be corrupted, because the fields in it are separated by commas as well. You can read more about it here: https://en.wikipedia.org/wiki/Comma-separated_values

**Comment by ProPontifex** [comment]
I understood that. Unfortunately, the site address includes a comma. Suggestions?

**Comment by freearhey** [comment]
You can either use any other source, or just upload the logo to one of the hosting sites like [imgur.com](https://imgur.com/).
